--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/HeavenPE/HideAccess
branches:
- master
projects:
  HideAccess:
    path: ""
    icon: "cross_stop_delete_denied_noaccess-512.png"
...
